DROP TABLE user_info;
CREATE TABLE user_info(
    user_id NVARCHAR2(20) CONSTRAINT pk_user_info_user_id PRIMARY KEY CHECK(LENGTH(user_id) >= 4)
    , password NVARCHAR2(20) NOT NULL CHECK(LENGTH(password) >= 8)
    , name NVARCHAR2(5) NOT NULL
    , email NVARCHAR2(20) NOT NULL UNIQUE
    , ROLE NVARCHAR2(3) DEFAULT '老馆' NOT NULL
);


CREATE TABLE SURVEY
(
SURVEY_ID NUMBER PRIMARY KEY NOT NULL 
,USER_ID NVARCHAR2(20)
,START_DATE DATE DEFAULT SYSDATE NOT NULL
,END_DATE DATE NOT NULL
,TITLE VARCHAR2(20) NOT NULL
,STATE VARCHAR(20) DEFAULT '老馆'
,SURVEY_ALLCNT NUMBER(10) DEFAULT 0 
,CONSTRAINT FK_SURVEY_USER_ID FOREIGN KEY(USER_ID) REFERENCES USER_INFO(user_id) ON DELETE SET NULL

);

CREATE TABLE SURVEY_OPTION
(
SURVEY_ID NUMBER   NOT NULL
,CONTENT_ID VARCHAR2(10)
,OPTION_CNT NUMBER(4)
,OPTION_CONTENT VARCHAR2(20)
,CONSTRAINT FK_OPTION_SURVEY_ID FOREIGN KEY(SURVEY_ID) REFERENCES SURVEY(SURVEY_ID) ON DELETE CASCADE
, CONSTRAINT survey_option_pk PRIMARY KEY(survey_id, content_id)
);




CREATE TABLE vote(
    SEQ NUMBER(10) NOT NULL PRIMARY KEY
    ,user_id NVARCHAR2(20) CONSTRAINT fk_user_info_user_id CHECK(LENGTH(user_id) >= 4)
    ,SURVEY_ID NUMBER(4) NOT NULL 
    ,ITEM_ID NUMBER(10) NOT NULL     
); 

CREATE SEQUENCE vote_seq
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 9999
       NOCYCLE
       NOCACHE
       NOORDER;
       
       INSERT INTO USER_INFO VALUES ('pilot','12345678','dwsa','eqwe','老馆');
       
       INSERT INTO SURVEY VALUES (1,'pilot',SYSDATE,'2023/10/1','eqwe','劝己',0);
       SELECT * FROM SURVEY;
       SELECT * FROM USER_INFO;
       
       INSERT INTO SURVEY_OPTION VALUES (1,'1',0,'test1');
       INSERT INTO SURVEY_OPTION VALUES (1,'2',0,'test2');
        SELECT * FROM SURVEY_OPTION;
       INSERT INTO VOTE VALUES (vote_seq.NEXTVAL,'pilot',1,'1');
       SELECT * FROM vote;
    